# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'rake', '~> 12.1'
gem 'test-unit', '~> 3.2', '>= 3.2.6'


# gem "rails"
